Rails.application.config.spotlight = OpenStruct.new
Rails.application.config.spotlight.activities = [
  "organise a sing-a-long movie night",
  "start an a capella group",
  "organise a battle of the bands",
  "grow a community garden",
  "plant some trees in the community",
  "make a community compost",
  "find communal spaces to grow fruit and veg",
  "look after local bees",
  "plant a communal herb garden",
  "start a community chicken coop",
  "bulk buy food",
  "weed a community garden",
  "repair footpaths",
  "start a seed library",
  "share bee friendly plant cuttings",
  "share some tools",
  "borrow some tools",
  "put up a wind turbine",
  "organise a street party",
  "organise a football competition",
  "learn how to repair a bike",
  "walk a neighbour's dog",
  "teach people a new skill",
  "meet new people and enjoy food together",
  "teach a recipe",
  "batch cook some food",
  "batch cook baby food",
  "take part in a local supper club",
  "host a potluck dinner",
  "organise a local nearly new toy swap",
  "start a local babysitting club",
  "start a local toy exchange",
  "organise a local baby clothes swap",
  "organise to close your street for a neighbourhood playday",
  "put on an outdoor cinema night for your neighbours"
]
